# Generated by Django 4.2.16 on 2024-09-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("staff", "Staff"),
                    ("client", "Client"),
                    ("provider", "Service Provider"),
                ],
                default="client",
                max_length=20,
            ),
        ),
    ]
