# Generated by Django 4.2.16 on 2024-09-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_customuser_bio_customuser_company_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="preferences",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
